### ISSUE TITLE
Add .gitignore file 

### ISSUE THREAD

**Issue by Rajkumar-justcoder** [Rajkumar-justcoder/Animated-name#10]

**Comment by mananchawla2005** [comment]
hey, its a simple html, css, js project... there is no room for adding gitignore file... if yes.. then it would just be blank file... please see to that...:)

**Comment by Rajkumar-justcoder** [comment]
No i means as many people use vs code and other software so some basic thing
So it adds .vscode and setting.jsonfile in repo

 As for that would be fine cause if some one fork and open thenthat things will apply insted of his/her default settings
And many more stuff

**Comment by mananchawla2005** [comment]
oh my bad! can you assign it to me?

**Comment by Rajkumar-justcoder** [comment]
Yeah sure 🚀
