### ISSUE TITLE
Set an array of object for the names.

### ISSUE THREAD

**Issue by ayobamiseun** [Rajkumar-justcoder/Animated-name#13]
Can we set an array of object for the names and map throught in in the index page.

**Comment by Rajkumar-justcoder** [comment]
Ah yeah we can  use json file or an array but json file would be great ig

**Comment by swaroopRajwal** [comment]
Can I work on this @Rajkumar-justcoder ?

**Comment by Rajkumar-justcoder** [comment]
yeah sure !!! Good to GO

**Comment by swaroopRajwal** [comment]
@Rajkumar-justcoder I guess you can mark this issue as closed now 🙄

**Comment by Rajkumar-justcoder** [comment]
yeah  sure forgot to close it
