### ISSUE TITLE
Feat: change heart emoji to icon 

### ISSUE THREAD

**Issue by Rajkumar-justcoder** [Rajkumar-justcoder/Animated-name#19]
from this 
![image](https://user-images.githubusercontent.com/83064473/193438033-314bd69e-9da8-45f0-8ed4-e5093844b2ed.png)

to 
![image](https://user-images.githubusercontent.com/83064473/193438044-6056de43-c430-40b3-907f-a155e9b47e57.png)

code in the the file only with icon and etc

**Comment by DevrajDC** [comment]
Hey, I would like to work on this. Thanks!

**Comment by Rajkumar-justcoder** [comment]
Yeah sure i will assign to you.

**Comment by trishitchar** [comment]
Can I work on this issue

**Comment by Rajkumar-justcoder** [comment]
> 

its already assigned and done also
