### ISSUE TITLE
Add Your name

### ISSUE THREAD

**Issue by Rajkumar-justcoder** [Rajkumar-justcoder/Animated-name#2]
Add your name with different colors themes animation etc u like 
Note: it will be  full screen name ( on scroll will display other name )

**Comment by Milind-Palaria** [comment]
hey @Rajkumar-justcoder  i would like to contribute to this. can u assign this to me?

**Comment by Rajkumar-justcoder** [comment]
> hey @Rajkumar-justcoder i would like to contribute to this. can u assign this to me?

yeah sure  @Milind-Palaria 
u got how to do that i means one name will display at a time on scroll second name will display

**Comment by samyaksand** [comment]
Hello, Im interested in working on this. Please assign me this issue.

**Comment by Rajkumar-justcoder** [comment]
your sure @samyaksand  so ahead

**Comment by abn15** [comment]
hello im interested, can u assign me the issue.

**Comment by stutimongia2024** [comment]
hey, @Rajkumar-justcoder, I would like to work on this issue. Please assign me the same.

**Comment by Rajkumar-justcoder** [comment]
yup sure @stutimongia2024
