### ISSUE TITLE
Feat: Add light and dark theme support

### ISSUE THREAD

**Issue by Rajkumar-justcoder** [Rajkumar-justcoder/Animated-name#21]
Add light and dark theme support + also add ss while pr

**Comment by trishitchar** [comment]
Hey, I would like to work on this. Thanks!

**Comment by Rajkumar-justcoder** [comment]
Yeah sure!!

**Comment by KaxitPandya** [comment]
@Rajkumar-justcoder  I would like to Contribute, Please assign this task to me

**Comment by Rajkumar-justcoder** [comment]
Yeah sure

**Comment by stutimongia2024** [comment]
I can add this feature to the website. Please assign me the same.

**Comment by Rajkumar-justcoder** [comment]
yup sure
