### ISSUE TITLE
Feat : Generate different text colors for names randomly.

### ISSUE THREAD

**Issue by Ritika-Agrawal811** [Rajkumar-justcoder/Animated-name#23]
I noticed that all names appear in same color and have same animation. So I would like to use CSS variables to make classes for different colors and set them to names randomly with JS.

**Comment by palaksv** [comment]
Please assign this issue to me.

**Comment by Ritika-Agrawal811** [comment]
@palaksv I created this issue so that it could be assigned to me. Please create your own issue.

**Comment by Rajkumar-justcoder** [comment]
Yeah that can be done @Ritika-Agrawal811  but pls keep theme dark as it is means dark theme

**Comment by Rajkumar-justcoder** [comment]
Hi @palaksv , What about this issue #26 
You can help there

**Comment by Ritika-Agrawal811** [comment]
> Yeah that can be done @Ritika-Agrawal811 but pls keep theme dark as it is means dark theme

I was thinking of adding color for text which look good with dark theme like neon colors. is that okay?

**Comment by Rajkumar-justcoder** [comment]
> > Yeah that can be done @Ritika-Agrawal811 but pls keep theme dark as it is means dark theme
> 
> I was thinking of adding bright colors for text which looks good with dark theme like yellow, green etc. is that okay?

Yeah thats would be also good but keep is simple and as u say 
But dont make it over contrast colors and that stuff
