### ISSUE TITLE
Fix: scroll thing

### ISSUE THREAD

**Issue by Rajkumar-justcoder** [Rajkumar-justcoder/Animated-name#26]
Currently its like one page come from left and snap to right change that to as we scroll and add snap to it like when user scroll then it direct scroll to that div with some smooth scroll

**Comment by ofaltins** [comment]
I'd like to contribute on this. Do you want the scroll to still be horizontal or change it to vertical scroll? @Rajkumar-justcoder

**Comment by Rajkumar-justcoder** [comment]
> I'd like to contribute on this. Do you want the scroll to still be horizontal or change it to vertical scroll? @Rajkumar-justcoder 

Change to vertical with snap effect and smooth scrolling
