### ISSUE TITLE
adding name 

### ISSUE THREAD

**Issue by BinilTomJose1278** [Rajkumar-justcoder/Animated-name#33]

**Comment by tajbaba999** [comment]
I want to work on this issue can you please assign me to this issue @BinilTomJose1278 
I am a beginner to open source contribution can you please help me out?

**Comment by BinilTomJose1278** [comment]
Hey rajkumar,
I would be happy to help, could you please tell me what kind of help u need
from me.
Thanking you in advance.

**Comment by tajbaba999** [comment]
Have assigned it to me @BinilTomJose1278 
can please tell me what kind of change require in "adding name"?

**Comment by BinilTomJose1278** [comment]
I  have gone into names.js file and I  have added my name as well along with other contributors. So after you accept my pull request it will be visible   in the deployed page.

**Comment by BinilTomJose1278** [comment]
I would like to work individually actually for this particular issue  if I can.

**Comment by Rajkumar-justcoder** [comment]
Hey @tajbaba999  and @BinilTomJose1278  you Both can add your names and link in name.js as other have added..

**Comment by tajbaba999** [comment]
Hey, @Rajkumar-justcoder I have added them, and can I make a pr?
can you provide any of your social media links I want to talk with you about personally?

**Comment by Rajkumar-justcoder** [comment]
> 

Hey @tajbaba999, you can go to my git profile there is twitter link there

**Comment by tajbaba999** [comment]
Hey, @Rajkumar-justcoder I can't message you back because you are not following back me on Twitter.
 Can you provider your other social media Links?
Any issue or wrong with my Pr?
