### ISSUE TITLE
Change README.md

### ISSUE THREAD

**Issue by rrsingh11** [Rajkumar-justcoder/Animated-name#4]
https://github.com/Rajkumar-justcoder/Animated-name/blob/4d7d2fc4f0bda6ea830ade231010f0ed1e8e563d/README.md?plain=1#L17-L20

**Comment by rrsingh11** [comment]
@Rajkumar-justcoder Can you add hacktoberfest label and assign it to me?

**Comment by rrsingh11** [comment]
I am sorry for that, Can you assign this issue to me after adding hacktoberfest label?

**Comment by Rajkumar-justcoder** [comment]
sure!
